server {
    charset              utf-8;
    client_max_body_size 1024M;

    listen 80;

    server_name app.local;
    root        /app/web;
    index       index.php;

    access_log app-access.log;
    error_log  app-error.log;

    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }

    location ~ \.(js|css|png|jpg|gif|swf|ico|pdf|mov|fla|zip|rar|ttf|woff|woff2)$ {
        try_files $uri =404;
    }

    location ~ ^/assets/.*\.php$ {
        deny all;
    }

    location ~ \.php$ {
        include       fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_pass  127.0.0.1:9000;
        # fastcgi_pass unix:/var/run/php-fpm.sock;
    }

    location ~* /\. {
        deny all;
    }
}