#!/usr/bin/env php
<?php

use yii\console\Application;
use yii\helpers\ArrayHelper;

defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';
require __DIR__ . '/config/bootstrap.php';

$config = ArrayHelper::merge(
        require __DIR__ . '/config/main.php',
        require __DIR__ . '/config/main-local.php',
        require __DIR__ . '/config/console.php',
        require __DIR__ . '/config/console-local.php',
);

$application = new Application($config);
$exitCode = $application->run();
exit($exitCode);
